config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.delete
    redirect_to articles_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Editing Article</h1>
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<%@articles.each do |article|%>
  <div class="py-3 border-bottom">
    <h1 class="title fs-3"><%=link_to article.title, article_path(article), style: "text-decoration: none;"%></h1>
    <p class="fs-5"><%=article.content[0..70]%> ...</p>
  </div>
<%end%>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<div class="d-flex justify-content-between">
  <h1 class="fs-2 border-bottom py-3 text-body"><%=@article.title%></h1>
  <div>
  <%=link_to "✏️", edit_article_path, style:"text-decoration: none;"%>
  <%=link_to "🗑", article_path(@article), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, style:"text-decoration: none;"%>
  </div>
</div>
<p class="fs-5 text-muted"><%=@article.content%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar d-flex justify-content-between px-3 border-bottom bg-light">
      <p class="fs-2" style="color: gray"><%= link_to "Wikinimous", articles_path, style:"text-decoration: none; color: gray"%></p>
      <p><%= link_to "New article", new_article_path, style:"text-decoration: none;"%></p>
    </div>
    <div class="container" style="width: 700px;">
      <%= yield %>
    </div>
  </body>
</html>